using Microsoft.IdentityModel.Tokens;
using RPG_Launcher.Model.Data;
using RPG_Launcher.Util;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.IdentityModel.Tokens.Jwt;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace RPG_Launcher.Model
{
    /// <summary>
    /// Singleton class that directly accesses the login API. Use this class via LoginApiService.Instance.
    /// </summary>
    public class LoginApiService
    {
        #region API SERVICE SINGLETON STUFF

        private static readonly LoginApiService _instance = new();
        /// <summary>
        /// The active LoginApiService singleton instance. Use this to access the LoginApiService.
        /// </summary>
        public static LoginApiService Instance { get => _instance; }

        static LoginApiService()
        {
            // Empty constructor for static singleton pattern. See fourth pattern for why this
            //  is necessary for thread safety: https://csharpindepth.com/articles/singleton
        }

        private LoginApiService()
        {
            // This is the actual constructor that is called.
        }

        #endregion



        /// <summary>
        /// Attempts to log in to the API using an existing refresh token. Makes an HTTPS request to the API
        ///  endpoint. Returns whether the operation was successful and updates AppStateData fields within
        ///  the method.
        /// </summary>
        /// <param name="refreshToken"> The stored refresh token, should be contained in AppStateData. </param>
        /// <returns> Whether the login attempt was successful. Automatically sets token fields in AppStateData. </returns>
        public bool TryLoginFromRefreshToken(string refreshToken)
        {
            // Ensure refreshToken is not empty.
            if (string.IsNullOrEmpty(refreshToken)) return false;

            string[]? tokens = TempLoginApiImitator.LoginFromRefreshToken(refreshToken, AppData.ClientGuid);
            if (tokens != null && tokens.Length == 2)
            {
                // We do not need to save username because logging in from refresh token is only allowed if the
                //  saved username matches the one stored within the refresh token (guaranteed to match here).

                // Pull tokens from API request (will be JSON in the future). Will check for response status code.
                AppData.AccessToken = tokens[0];
                AppData.RefreshToken = tokens[1];  // Replace existing with new (re-generated by server).
                return true;
            }

            // If our login failed for any reason, we should reset our refresh token to empty.
            AppData.RefreshToken = string.Empty;
            return false;
        }

        /// <summary>
        /// Attemps to log in to the API normally with username and password. Makes an HTTPS request to
        ///  the API endpoint. Returns whether the operation was successful and updates AppStateData fields
        ///  within the method.
        /// </summary>
        /// <param name="credential"> A NetworkCredential object instantiated with the username and password. </param>
        /// <returns> Whether the login attempt was successful. Automatically sets token fields in AppStateData. </returns>
        public bool Login(NetworkCredential credential)
        {
            // Ensure credentials are not empty.
            if (string.IsNullOrEmpty(credential.UserName) || string.IsNullOrEmpty(credential.Password)) return false;

            // Actual login API endpoint will take username and password strings, and returns two token strings.
            string[]? tokens = TempLoginApiImitator.Login(credential.UserName, credential.Password, AppData.ClientGuid);
            if (tokens != null && tokens.Length == 2)
            {
                // Store saved username after successful login (must be done before refresh token is written).
                AppData.SavedUsername = credential.UserName;

                // Pull tokens from API request (will be JSON in the future). Will check for response status code.
                AppData.AccessToken = tokens[0];
                AppData.RefreshToken = tokens[1];

                return true;
            }

            return false;
        }

        /// <summary>
        /// Attempts to register a new user to the API with an email, username, and password. Makes an HTTPS
        ///  request to the API endpoint. Returns a status code describing attempt success or failure and
        ///  updates AppData token fields within the method.
        /// </summary>
        /// <param name="email"> The email associated with the account attempting to be registered. </param>
        /// <param name="credential"> A NetworkCredential object instantiated with the username and password. </param>
        /// <returns> A status code describing the result of the registration attempt. 0 for success, >0 for failure. </returns>
        public int Register(string email, NetworkCredential credential)
        {
            // Ensure email and credentials are not empty.
            if (string.IsNullOrEmpty(credential.UserName) || string.IsNullOrEmpty(credential.Password)
                || string.IsNullOrEmpty(email))
            {
                return 1;      // 1 for invalid input
            }

            // Actual register API endpoint will take email, username, and string, then returns both tokens.
            var tokens = TempLoginApiImitator.Register(email, credential.UserName, credential.Password, AppData.ClientGuid);
            if (tokens != null && tokens.Length == 2)
            {
                // Store saved username after successful login (must be done before refresh token is written).
                AppData.SavedUsername = credential.UserName;
                
                // Pull tokens from API request (will be JSON in the future). Will check for response status code.
                AppData.AccessToken = tokens[0];
                AppData.RefreshToken = tokens[1];
                return 0;       // 0 for success
            }

            return 2;           // 2 for generic registration failure (email or username unavailable)
        }

        /// <summary>
        /// Logs out of the API. Makes an HTTPS request to the API endpoint. Logout is always successful, even
        ///  if no acknowledgement is received from the server. Automatically invalidates any stored tokens.
        /// </summary>
        public void Logout()
        {
            // Call the API logout endpoint, passing it our access token so it can find us (logout requires valid access token).
            // This method will not need to return anything. If we call this logout endpoint with an access token that the
            //  server cannot find (somehow), it does not matter because the server will not allow us to use any endpoint
            //  anyway. The access token will contain our username which is used to remove our refresh token as well (logout
            //  should log the user out of everything).

            TempLoginApiImitator.Logout(AppData.AccessToken);

            // After logout, reset access and refresh tokens to empty.
            AppData.AccessToken = string.Empty;
            AppData.RefreshToken = string.Empty;
        }
    }
}
