using Microsoft.IdentityModel.Tokens;
using RPG_Launcher.Model.Data;
using RPG_Launcher.Util;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.IdentityModel.Tokens.Jwt;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace RPG_Launcher.Model
{
    public class LoginApiService
    {
        #region API SERVICE SINGLETON STUFF

        private static readonly LoginApiService _instance = new();
        public static LoginApiService Instance { get => _instance; }

        static LoginApiService()
        {
            // Empty constructor for static singleton pattern. See fourth pattern for why this
            //  is necessary for thread safety: https://csharpindepth.com/articles/singleton
        }

        private LoginApiService()
        {
            // This is the actual constructor that is called.
        }

        #endregion



        public bool TryLoginFromRefreshToken(string refreshToken)
        {
            // Ensure refreshToken is not empty.
            if (string.IsNullOrEmpty(refreshToken)) return false;

            string[]? tokens = TempLoginApiImitator.LoginFromRefreshToken(refreshToken);
            if (tokens != null && tokens.Length == 2)
            {
                // Pull tokens from API request (will be JSON in the future). Will check for response status code.
                AppStateData.AccessToken = tokens[0];
                AppStateData.RefreshToken = tokens[1];  // Replace existing with new (re-generated by server).
                return true;
            }

            return false;
        }

        public bool Login(NetworkCredential credential)
        {
            // Ensure credentials are not empty.
            if (string.IsNullOrEmpty(credential.UserName) || string.IsNullOrEmpty(credential.Password)) return false;

            // Actual login API endpoint will take username and password strings, and returns two token strings.
            string[]? tokens = TempLoginApiImitator.Login(credential.UserName, credential.Password);
            if (tokens != null && tokens.Length == 2)
            {
                // Pull tokens from API request (will be JSON in the future). Will check for response status code.
                AppStateData.AccessToken = tokens[0];
                AppStateData.RefreshToken = tokens[1];
                return true;
            }

            return false;
        }

        public bool Register(string email, NetworkCredential credential)
        {
            // Ensure email and credentials are not empty.
            if (string.IsNullOrEmpty(credential.UserName) || string.IsNullOrEmpty(credential.Password)
                || string.IsNullOrEmpty(email))
            {
                return false;
            }

            // Actual register API endpoint will take email, username, and string, then returns both tokens.
            var tokens = TempLoginApiImitator.Register(email, credential.UserName, credential.Password);
            if (tokens != null && tokens.Length == 2)
            {
                // Pull tokens from API request (will be JSON in the future). Will check for response status code.
                AppStateData.AccessToken = tokens[0];
                AppStateData.RefreshToken = tokens[1];
                return true;
            }

            return false;
        }

    }
}
